### ISSUE TITLE
OverlappingInstances is deprecated in GHC-7.10

### ISSUE THREAD

**Issue by bergey** [diagrams/monoid-extras#15]
The module-wide pragma is deprecated in favor of per-instance pragmas.  More details [in trac](https://ghc.haskell.org/trac/ghc/ticket/9242).  Unfortunately, I'm not sure which pragmas are correct for which instances in `MList`.

**Comment by isomorphism** [comment]
Looks like you already fixed this, but FWIW you could also eliminate `OverlappingInstances` entirely and use closed type families + vinyl's index trick.

**Comment by byorgey** [comment]
At the moment, we still want to support at least GHC 7.6, and closed type families were only introduced in 7.8.

**Comment by byorgey** [comment]
Looks like this was fixed by https://github.com/diagrams/monoid-extras/commit/a272a42e52601a38a0c88584de36e22891ba982d .
