### ISSUE TITLE
New release for 7.10?

### ISSUE THREAD

**Issue by shlevy** [diagrams/monoid-extras#19]
Seems like master is tested against 7.10, can we get a new hackage release?

**Comment by byorgey** [comment]
Yep, we're hard at work on a new diagrams release, should be any day now.
Out of curiosity, do you have a specific need/use for monoid-extras other
than building diagrams?

**Comment by shlevy** [comment]
@byorgey Just trying to get https://github.com/imalsogreg/arte-ephys building :smile:

**Comment by byorgey** [comment]
Woah, yet another cool use of diagrams I didn't know about!

That's the problem with having good documentation.  People just use your libraries and get on with life, and you never hear about it =)

**Comment by byorgey** [comment]
@shlevy Oh, actually, I just realized I shouldn't get your hopes up too much.  What we are working on is a new major (backwards-incompatible) release of diagrams.  So the new release will build on GHC-7.10, but arte-ephys will almost certainly not build with it. (Though we are preparing detailed instructions for upgrading, so it should not be too bad.) After the new diagrams release we may look into making new point releases in the diagrams 1.2 series, to give people on GHC 7.10 more options.

**Comment by shlevy** [comment]
Oh yeah, I'm collaborating closely with @imalsogreg the maintainer and I expect we'll be able to bring it up to date once the new release is out.

**Comment by byorgey** [comment]
OK, great.  We'll be happy to help with upgrading as well.
