### ISSUE TITLE
ghc-8.4.1 support?

### ISSUE THREAD

**Issue by claudeha** [diagrams/monoid-extras#35]
The dependencies forbid it and it fails to build with `cabal install --allow-newer=base`

    [ 5 of 12] Compiling Data.Monoid.Endomorphism ( src/Data/Monoid/Endomorphism.hs, dist/dist-sandbox-6ff59ee5/build/Data/Monoid/Endomorphism.o )
    
    src/Data/Monoid/Endomorphism.hs:38:24: error:
        Not in scope: type constructor or class ‘Monoid’
        Perhaps you want to add ‘Monoid’ to the import list
        in the import of ‘Prelude’
        (src/Data/Monoid/Endomorphism.hs:25:1-41).
       |
    38 | instance Category k => Monoid (Endomorphism k a) where
       |                        ^^^^^^
    cabal: Leaving directory '/tmp/cabal-tmp-12924/monoid-extras-0.4.2'

**Comment by claudeha** [comment]
git sources work, so this is fixed already, just needs a release...

**Comment by byorgey** [comment]
Sorry for the delay, `monoid-extras-0.4.3` is now on Hackage.
