### ISSUE TITLE
Release New Version?

### ISSUE THREAD

**Issue by prikhi** [diagrams/monoid-extras#46]
Hi, seems like this has dropped out of stackage because of the upper-bound on the `base` package.

This has been fixed in master, but the latest released version still has the `base < 4.14`. Could we have a new release so I can upgrade some dependent-packages to GHC 8.10?

Thanks!

**Comment by prikhi** [comment]
ping @byorgey

**Comment by byorgey** [comment]
@prikhi  Working on it -- apologies for the delay!

**Comment by byorgey** [comment]
Updated bounds for `monoid-extras-0.5.1` on Hackage.
