### ISSUE TITLE
Transitive group actions

### ISSUE THREAD

**Issue by turion** [diagrams/monoid-extras#53]
Would you accept a PR that adds (simply/free/regular) transitive group actions, also known as torsors or principal homogeneous spaces? Basically:

```haskell
class (Group m, Action m s) => TransitiveAction m s where
  difference :: s -> s -> m
```

I'm requiring `Group m` because if `m` is only a monoid we can define `m1 ~~ m2 = (s `act` m1) `difference` (s `act` m2)` anyways, so it makes more sense to require the constraint and demand it to be equal to this formula by the laws of group actions.

See https://github.com/Taneb/groups/issues/15.

**Comment by byorgey** [comment]
Sure!

**Comment by turion** [comment]
I'm a bit undecided with the naming, but "Torsor" is a good compromise between popularity and shortness
